framework: all
skip-download: true
soft-fail: true
summary-position: bottom
download-external-modules: false
secrets-history-timeout: 8h
skip-check:
  - CKV_TF_1 # OTC-Code Modules are versioned from a trusted source

