name: Action OpenTofu Tests
on:
  workflow_dispatch:
  push:
    paths:
      - '**.sh'
      - '**.yml'
  pull_request:

permissions:
  # required for all workflows
  contents: write
  checks: write
  pull-requests: write
  discussions: write
  statuses: write
  id-token: write # This is required for requesting the JWT for oidc AUthentication


jobs:
  base:
    name: Base Test
    uses: otc-code/code-workflows/.github/workflows/workflow_test.yml@main
    secrets: inherit
  dev_aws:
    name: AWS Test
    if: ${{ github.event_name == 'pull_request' }}
    uses: ./.github/workflows/test_cases.yml
    secrets: inherit
    with:
      RUNNER: 'STATIC'
      ENV: 'CODE-TST-AWS'
      PROVIDER: 'aws'
      DIR: 'iac-code/plain'
